# Project Euler Problem 2
# =======================
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not 
# exceed four million.

from math import floor
firstTerm  = 1
secondTerm = 2
newTerm    = 3

maximum = 4E6
total   = 2

while (newTerm <= maximum):

  # generates each term in Fibonacci sequence
  newTerm = firstTerm + secondTerm 

  # finds remainder of division by 2 (=0 if even)
  remainderOfDivision = newTerm-(2*(floor(newTerm/2.))) 
  if (remainderOfDivision == 0):
    total+=newTerm

  # readies variables for next iteration
  firstTerm  = secondTerm
  secondTerm = newTerm

print total
