## SOLVED
#
# Project Euler Problem 45
# ========================
# Triangle, pentagonal, and hexagonal numbers are
# generated by the following formulae:
#
# Triangle    Tn=n(n+1)/2     1, 3,  6, 10, 15, ...
# Pentagonal  Pn=n(3n-1)/2    1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n-1)      1, 6, 15, 28, 45, ...
#
# It can be verified that T285=P165=H143=40755.
#
# Find the next triangle number that is also
# pentagonal and hexagonal.
#


from math import sqrt

def isTriangle(Tn):
    k=(-1+sqrt(1+(8*Tn)))/2
    if k==int(k):
        return True
    else: return False

def isPentagonal(Pn):
    k=(1+sqrt(1+(24*Pn)))/6
    if k==int(k):
        return True
    else: return False
    
def isHexagonal(Hn):
    k=(1+sqrt(1+(8*Hn)))/4
    if k==int(k):
        return True
    else: return False

# generate a big list of hexagonal numbers
# since they increase fastest, they are rarer
# for a given section of the number line
hxgn=[((n*n*2) - n) for n in range(144,100000)]

for h in hxgn:
    if isPentagonal(h):
        if isTriangle(h):
            print 'Finished!'
            print h
            exit
